# Generated by Django 4.1.5 on 2023-02-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_usersbookings_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslots',
            name='isAvailable',
            field=models.BooleanField(default=True, verbose_name='Is Available?'),
        ),
        migrations.AlterField(
            model_name='parkingslots',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('FREE', 'Free')], default='FREE', max_length=50, verbose_name='Status'),
        ),
    ]
