# Generated by Django 4.1.5 on 2023-03-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_parkingslots_isavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbookings',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('USING', 'Using'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=10, verbose_name='Status'),
        ),
    ]
