# Generated by Django 4.1.5 on 2023-03-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_alter_parkingslots_isavailable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Request At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Request ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Long URL')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=50, verbose_name='Payment Status')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.usersbookings')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
