# Generated by Django 4.1.5 on 2023-03-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_usersbookings_status'),
        ('payments', '0002_rename_payment_paymentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='booking',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='booking',
            field=models.ManyToManyField(related_name='payments', to='bookings.usersbookings'),
        ),
    ]
