import '@/styles/globals.css'
import Head from 'next/head'
import SnackBarContext from 'contexts/SnackBarContext'
import { CookiesProvider } from 'react-cookie';

export default function App({ Component, pageProps }) {
  return (
    <>
      <CookiesProvider>
        <SnackBarContext>
          <Head>
            <title>Book Parking</title>
            <meta name="description" content="Generated by Darshan Prajapati" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo-icon.png" />
          </Head>
          <Component {...pageProps} />
        </SnackBarContext>
      </CookiesProvider>
      
    </>
  )
}
